engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 65
  shellcheck:
    enabled: true
checks:
  method-count:
    enabled: false
ratings:
   paths:
   - "**.js"