engines:
  tslint:
    enabled: true
    config: tslint.json
  shellcheck:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        typescript:
          mass_threshold: 70
          count_threshold: 3

ratings:
  paths:
    - '**.ts'

exclude_paths:
  - node_modules
  - typings
  - coverage
  - dist
