version: '2'

checks:
  similar-code:
    enabled: false
  file-lines:
    enabled: false
  method-count:
    enabled: false

exclude_patterns:
  - node_modules/
  - coverage/
  - dist/
  - **/test/
  - **/*.d.ts
