root: true

env:
  node: true
  browser: true
  jest/globals: true

globals:
  page: true
  browser: true
  context: true

extends:
  - airbnb-base
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - plugin:jest/recommended

parser: '@typescript-eslint/parser'

ignorePatterns:
  - node_modules/
  - dist/
  - '**/rollup.config.js'
  - '**/jest.config*.js'
  - '**/scripts/*.ts'
  - '*d.ts'

plugins:
  - '@typescript-eslint'
  - import

rules:
  import/no-default-export: error
  import/prefer-default-export: off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/explicit-module-boundary-types': off
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - 'scripts/*.js'
        - '**/test/**/*.ts'
  import/extensions:
    - error
    - never
    - json: always
  camelcase:
    - error

overrides:
  - files:
      - '**/*.ts'
      - '**/*.tsx'
    rules:
      camelcase: 'off'
  - files:
      - '**/test/**/*.ts'
    rules:
      '@typescript-eslint/no-var-requires': 'off'
      global-require: 'off'
      jest/no-mocks-import: 'off'
  - files:
      - '**/__mocks__/**/*.ts'
    rules:
      import/no-default-export: 'off'

settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .ts
