env:
  node: true
  browser: true
  jest/globals: true

globals:
  page: true
  browser: true
  context: true

extends:
  - airbnb-base
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
  - plugin:jest/recommended

parser: '@typescript-eslint/parser'

ignorePatterns:
  - node_modules/
  - dist/
  - '**/rollup.config.js'
  - '**/jest.config*.js'
  - '**/scripts/*.ts'
  - '*d.ts'

plugins:
  - '@typescript-eslint'
  - import

rules:
  import/no-default-export: error
  import/prefer-default-export: off
  '@typescript-eslint/explicit-function-return-type': off
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - '**/test/**/*.ts'
  import/extensions:
    - error
    - never
    - json: always

settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .ts
