env:
  node: true
  browser: true
  jest: true
parser: babel-eslint
extends:
  - airbnb
  - plugin:jest/recommended
rules:
  arrow-body-style: [2, "as-needed"]
  no-param-reassign: ["error", {"props":false}]
  import/prefer-default-export: 1
plugins:
  - jest
