export enum AccessLevel {
  NO_ACCESS = 0,
  MINIMAL_ACCESS = 5,
  GUEST = 10,
  PLANNER = 15,
  REPORTER = 20,
  SECURITY_MANAGER = 25,
  DEVELOPER = 30,
  MAINTAINER = 40,
  OWNER = 50,
  ADMIN = 60,
}
