#!/bin/bash

## Running the init logic for gitlab. See PR# for splitting this wrapper file into two pieces
/bin/bash init/init &>/dev/null

echo Sleep for 30 seconds to ensure all services are running
sleep 30

echo Initalize test token and user
PERSONAL_ACCESS_TOKEN="$(gitlab-rails r /init/test.rb)"

echo Tail and wait
gitlab-ctl tail&
wait