name: 'Base Pipeline'

on:
  pull_request:
    branches:
      - main

env:
  NX_REJECT_UNKNOWN_LOCAL_CACHE: 0
  NODE_VERSION: 20

jobs:
  warmup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile

  lint:
    runs-on: ubuntu-latest
    needs:
      - warmup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'
      - name: Lint
        run: yarn lint

  format:
    runs-on: ubuntu-latest
    needs:
      - warmup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'
      - name: Format
        run: yarn format

  build:
    runs-on: ubuntu-latest
    needs:
      - warmup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'
      - name: Cache NX cache
        uses: actions/cache@v4
        with:
          path: .nx/cache
          key: ${{ runner.os }}-nx-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-nx-
      - name: Build Packages
        run: yarn build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: |
            packages/core/dist/
            packages/cli/dist/
            packages/rest/dist/
            packages/requester-utils/dist/
