on: [pull_request, push]

jobs:
  gitlab-ci:
    runs-on: ubuntu-latest

    container:
      image:  alpine/git

    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # - name: Assign Trigger Branch Context (!Fork PR)
      #   if: ${{ github.event_name != 'pull_request_target' }}
      #   run: |
      #     echo "{TRIGGER_BRANCH}={${{env.GITHUB_HEAD_REF_SLUG}}}" >> $GITHUB_ENV

      - name: Assign Trigger Branch Context (Fork PR)
        if: ${{ github.event_name != 'pull_request_target' }}
        run: |
          echo "{TRIGGER_BRANCH}={${{github.run_id}}-${{env.GITHUB_REF_NAME}}}" >> $GITHUB_ENV
          git branch ${{env.TRIGGER_BRANCH}} ${{ github.event.pull_request.head.sha }}
          git push origin ${{env.TRIGGER_BRANCH}}

      # - name: Update Mirror
      #   run: |
      #     curl -X POST https://*******/projects/elexis%2Felexis-3-core/mirror/pull

      # - name: Await CI/CD Pipeline
          # run: |
          # See if pipeline has started for branch, if not start it.
          # Poll until complete
          

      # - name: Clean up
      #   if: ${{ github.event_name == 'pull_request_target' }}
      #   run: |
      #     git branch -d ${{env.TRIGGER_BRANCH}}
      #     git push origin --delete ${{env.TRIGGER_BRANCH}}
